[package]
name = "xtask"
version = "1.0.0"
authors = ["Gediminas Lūžys <163294+gediminas@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[[bin]]
name = "xtask"
path = "xtask.rs"

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
